import type { Metadata, Viewport } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Articulate — Executive Communication & Clarity",
  description:
    "An articulation training course with AI coaching. Practice executive communication and get specific, rubric-based feedback on clarity, concision, structure, precision, and presence.",
  manifest: "/manifest.webmanifest",
  // Makes an iPad "Add to Home Screen" install launch full-screen as a
  // standalone app rather than inside Safari.
  appleWebApp: {
    capable: true,
    title: "Articulate",
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  themeColor: "#b5512f",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-grain min-h-screen font-sans antialiased">
        <header className="border-b border-ink/10">
          <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
            <Link href="/" className="group flex items-baseline gap-2">
              <span className="font-serif text-xl font-semibold tracking-tight">
                Articulate
              </span>
              <span className="text-xs uppercase tracking-widest text-ink-mute">
                clarity training
              </span>
            </Link>
            <Link
              href="/#modules"
              className="text-sm text-ink-mute transition-colors hover:text-accent"
            >
              Modules
            </Link>
          </div>
        </header>
        <main className="mx-auto max-w-4xl px-6 py-10">{children}</main>
        <footer className="border-t border-ink/10">
          <div className="mx-auto max-w-4xl px-6 py-6 text-xs text-ink-mute">
            Articulate · AI-coached practice for executive communication. Feedback is
            generated by Claude and meant as practice, not gospel.
          </div>
        </footer>
      </body>
    </html>
  );
}
